apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
  namespace: default
spec:
  replicas: 4
  strategy:
    canary:
      analysis:
        templates:
        - templateName: error-rate
        startingStep: 1
        args:
        - name: service-name
          value: demo-app
      steps:
      - setWeight: 20
      - pause: {duration: 25s}
      - setWeight: 50
      - pause: {duration: 25s}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: demo-app:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: APP_VERSION
          value: "v1.0.0 (Stable & Healthy)"
        - name: COLOR_THEME
          value: "#00f0ff" # Neon Blue
        - name: SIMULATE_FAILURE
          value: "false"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
