apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gauravshinde2162006-hash/Docker_Project.git
    targetRevision: main
    path: k8s/argo-rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - CreateNamespace=true
